### ISSUE TITLE
More information on each Pokémon

### ISSUE THREAD

**Issue by yuvi3000** [andreshazard/Telegram-PokeBotGo#2]
Here's what shows for Kabuto on Bulbapedia, specifically for Pokémon Go:

Base Stamina: 60
Base Attack: 148
Base Defense: 142
Egg Distance: 10 km
Evolution Requirement: 50 Kabuto candy
Fast Attacks: Scratch, Mud Shot
Special Attacks: Ancient Power, Aqua Jet, Rock Tomb

I think that stuff should be shown and the info is relatively easy to access.

**Comment by yuvi3000** [comment]
Add default catch rate
Add a basic description of rarity

**Comment by andreshazard** [comment]
@yuvi3000  same here, where should I get this information. Hopefully all pokemons are in one single page.

**Comment by yuvi3000** [comment]
Right now, I think the easiest thing to do would be to check and update each Pokémon :(

I don't know if you'll find all that on one page just yet.

**Comment by andreshazard** [comment]
@yuvi3000 For now I'm gonna just add : 
- Base Attack 
- Base Defense
- Stamina 
- Max CP

I'm adding this because I found this list : 
https://pokemongo.gamepress.gg/pokemon-list-advanced

which made it really easy. 
I'll add the other stuff if I see that the bot is being used a lot.
