### ISSUE TITLE
Weakness, Effectiveness and Resistance

### ISSUE THREAD

**Issue by yuvi3000** [andreshazard/Telegram-PokeBotGo#3]
Add "Effective against"
Add " Weak against"
Add "Resistant to"
Add "Unaffected by"

**Comment by yuvi3000** [comment]
This was added to the /type function, but it does not include resistance and not effective.

This also may defer per Pokémon so it may be better to show this for every Pokémon in the /pokemon function.

e.g. Aerodactyl is primarily Rock-type but is weak against Electricity. If you check /type rock and /type flying, you wouldn't know which effect Electric attacks have.

**Comment by andreshazard** [comment]
@yuvi3000 Do you know which is the best source material to get this information ? 
If we can get a list of the all the pokemons with this information on one page it would be nice, is faster that sites that offer a single page for each pokemon, because that way I need to go through all the pages one by one to get the information.

**Comment by yuvi3000** [comment]
I don't have a better source, unfortunately :(

I totally understand the situation. You're doing this for free in your spare time. I don't expect you to be working on it 24/7 and what you've already released so far is pretty helpful :)

I guess it's just a bit of frustration to gather that info

**Comment by Avenged7x85** [comment]
Hello!
I just installed the Telegram bot and was messing around with it - thought I would take a look at the gethub to check out known issues to see if I could help in any way. 
Here is a single page talking about all of the current type  sets with information on strong against, weak against, and the like.  Let me know if this helps you out in any way.

http://bulbapedia.bulbagarden.net/wiki/Type

**Comment by andreshazard** [comment]
@Avenged7x85 Thanks a lot for the help!. 
The bot already has like a type chart information command /type fire for example. 
But I think the point of @yuvi3000  is that type weakness and strength is different from pokemons weakness and strength. 
So I need to put that info into the database and for that I would be useful to have all the info in one single page so I can copy and paste that info in a text format, it sounds lazy but is much more faster that way. 
I'm not sure if that makes sense.

**Comment by Avenged7x85** [comment]
right right, I do understand.
My day has quite a bit of downtime during normal business hours. If you are
able to provide a format that is easier for you to import I could perhaps
get that worked out for you.

**Comment by andreshazard** [comment]
@Avenged7x85  thanks! 
Do you have sql knowledge ? 
If not, no worries we can figure out a way =)

**Comment by Avenged7x85** [comment]
I most likely know enough that if you were to type up a rough template I
could follow along and get that task done.
I work in the IT field and have had to troubleshoot web applications, plus
we have a few programmers here if I run into a snag.

**Comment by andreshazard** [comment]
Awesome! 
Can you send me an email here : andres.hazard@gmail.com so I can have yours and send you more info as soon as I can.

**Comment by andreshazard** [comment]
I'm closing this for now and I'll reopen if make progress.
