### ISSUE TITLE
National Pokédex number instead of name

### ISSUE THREAD

**Issue by yuvi3000** [andreshazard/Telegram-PokeBotGo#4]
Let the user call the same command by typing in the National Pokédex number instead of the Pokémon name? It's not necessary, but it'd be cool to know which one comes after another Pokémon if you're trying to remember

**Comment by andreshazard** [comment]
@yuvi3000  I added the command "/pokedex" 
Feel free to try it out.

**Comment by yuvi3000** [comment]
Awesome! Works well!
